name: united102
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  flutter_svg: ^2.0.7
  provider: ^6.0.5


  json_annotation: ^4.8.1

  #Firebase tools
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3

  #
  shared_preferences: ^2.1.2


  #Routes
  go_router: ^8.0.5


 #State manger
  flutter_bloc: ^8.1.3

  #Utils
  line_icons: ^2.0.1
  google_nav_bar: ^5.0.6

  flutter_swipe_action_cell: ^3.1.1
  injectable: ^2.1.2
  flutter_screenutil: ^5.8.4
  dropdown_button2: ^2.1.4
  dio: ^5.2.1+1
  platform_info: ^4.0.0
  flutter_localizations:





    sdk: flutter
  intl: any
  flutter_local_notifications: ^14.1.1
  flutter_smart_dialog: ^4.9.2
  extended_masked_text: ^2.3.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0



flutter:


  uses-material-design: true
  generate: true


  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/nav_bar_icons/
    - assets/specialNeedsSvg/
    - assets/setting_icons/






