// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5osRJwZjqlEyhd06n7k72abJrSJo71jc',
    appId: '1:617035942335:web:975cdae2b7172d2201b90a',
    messagingSenderId: '617035942335',
    projectId: 'seo-rsk-bank',
    authDomain: 'seo-rsk-bank.firebaseapp.com',
    storageBucket: 'seo-rsk-bank.appspot.com',
    measurementId: 'G-V48SJGQZZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaRbR4a-kf9JsR3EwTj5eFKnWn1LNjbYs',
    appId: '1:617035942335:android:b2b8212f103a2cc501b90a',
    messagingSenderId: '617035942335',
    projectId: 'seo-rsk-bank',
    storageBucket: 'seo-rsk-bank.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Pl3WPTl993F6r4ta7uLEi4Uie8R-liE',
    appId: '1:617035942335:ios:9ebe546d494a78c601b90a',
    messagingSenderId: '617035942335',
    projectId: 'seo-rsk-bank',
    storageBucket: 'seo-rsk-bank.appspot.com',
    iosClientId: '617035942335-fhniu3ru2jqcppb233b432r6k8a98f96.apps.googleusercontent.com',
    iosBundleId: 'com.example.united102',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Pl3WPTl993F6r4ta7uLEi4Uie8R-liE',
    appId: '1:617035942335:ios:32760dc28ab0a11801b90a',
    messagingSenderId: '617035942335',
    projectId: 'seo-rsk-bank',
    storageBucket: 'seo-rsk-bank.appspot.com',
    iosClientId: '617035942335-t7o7kgc0emh7aqk4rvftsf8a75nmad3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.united102.RunnerTests',
  );
}
